name: build

on:
  push:
    branches: [ main ]
    tags: ['*']
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: a2stuff/build-install-ca65-action@v1
      - uses: a2stuff/build-install-cadius-action@v1

      - name: build
        env:
          TERM: xterm-256color
        run: >
          make && make package

      - name: deploy new version
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1.11.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "out/intbasic_system.po,out/intbasic_system.2mg"
